export const emojiToIconKey: Record<string, string> = {
  '🏃': 'Footprints',
  '📖': 'BookOpen',
  '🧘': 'Brain',
  '💪': 'Dumbbell',
  '🎯': 'Target',
  '📝': 'PenLine',
  '💤': 'Bed',
  '🥗': 'Salad',
  '💧': 'Droplets',
  '🧠': 'Brain',
  '🎨': 'Palette',
  '🎵': 'Music',
  '📱': 'Smartphone',
  '⏰': 'AlarmClock',
  '🌿': 'TreePine',
  '🧹': 'Trash2',
  '💰': 'Coins',
  '❤️': 'Heart',
  '🏋️': 'Dumbbell',
  '🚴': 'Bike',
  '📚': 'BookOpen',
  '✍️': 'Pencil',
  '🗂️': 'FolderOpen',
  '🗣️': 'MessageCircle',
  '🌅': 'Sunrise',
  '🚿': 'ShowerHead',
  '🍎': 'Apple',
  '🩺': 'Stethoscope',
  '🐕': 'Dog',
  '🎮': 'Gamepad2',
  '📸': 'Camera',
  '✈️': 'Plane',
  '🎸': 'Guitar',
  '🧑‍💻': 'Code',
  '📊': 'BarChart3',
  '🧑‍🎓': 'GraduationCap',
  '🧑‍🍳': 'ChefHat',
  '🧑‍⚕️': 'Stethoscope',
  '⚡': 'Zap',
  '🏥': 'Stethoscope',
  '📁': 'FolderOpen',
};

export function migrateIcon(emoji: string): string | undefined {
  return emojiToIconKey[emoji];
}
